use serde::{Serialize, Serializer};
use std::fmt;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum Language {
    Na = 0x00,
    Alb = 0x01,
    Bre = 0x02,
    Cat = 0x03,
    Hrv = 0x04,
    Cym = 0x05,
    Ces = 0x06,
    Dan = 0x07,
    Deu = 0x08,
    Eng = 0x09,
    Spa = 0x0A,
    Epo = 0x0B,
    Est = 0x0C,
    Eus = 0x0D,
    Fae = 0x0E,
    Fra = 0x0F,
    Fry = 0x10,
    Gle = 0x11,
    Glg = 0x13,
    Isl = 0x14,
    Ita = 0x15,
    Lat = 0x17,
    Lav = 0x18,
    Lux = 0x19,
    Lit = 0x1A,
    Hun = 0x1B,
    Mlt = 0x1C,
    Nld = 0x1D,
    Nor = 0x1E,
    Oci = 0x1F,
    Pol = 0x20,
    Por = 0x21,
    Ron = 0x22,
    Roh = 0x23,
    Srp = 0x24,
    Slk = 0x25,
    Slv = 0x26,
    Fin = 0x27,
    Swe = 0x28,
    Tur = 0x29,
    Zul = 0x45,
    Vie = 0x46,
    Uzb = 0x47,
    Urd = 0x48,
    Ukr = 0x49,
    Tha = 0x4A,
    Tel = 0x4B,
    Tat = 0x4C,
    Tam = 0x4D,
    Tgk = 0x4E,
    Swa = 0x4F,
    Som = 0x51,
    Sin = 0x52,
    Sho = 0x53,
    Rus = 0x56,
    Que = 0x57,
    Pst = 0x58,
    Pan = 0x59,
    Per = 0x5A,
    Ori = 0x5C,
    Nep = 0x5D,
    Mar = 0x5F,
    Mol = 0x60,
    Mal = 0x61,
    Mkd = 0x63,
    Kor = 0x65,
    Khm = 0x66,
    Kaz = 0x67,
    Jpn = 0x69,
    Ind = 0x6A,
    Hin = 0x6B,
    Heb = 0x6C,
    Gre = 0x70,
    Chi = 0x75,
    Bul = 0x77,
    Ben = 0x78,
    Arm = 0x7D,
    Ara = 0x7E,
    Amh = 0x7F,
    Unknown = 0xFF,
}

impl From<u8> for Language {
    fn from(value: u8) -> Self {
        match value {
            0x00 => Language::Na,
            0x01 => Language::Alb,
            0x02 => Language::Bre,
            0x03 => Language::Cat,
            0x04 => Language::Hrv,
            0x05 => Language::Cym,
            0x06 => Language::Ces,
            0x07 => Language::Dan,
            0x08 => Language::Deu,
            0x09 => Language::Eng,
            0x0A => Language::Spa,
            0x0B => Language::Epo,
            0x0C => Language::Est,
            0x0D => Language::Eus,
            0x0E => Language::Fae,
            0x0F => Language::Fra,
            0x10 => Language::Fry,
            0x11 => Language::Gle,
            0x13 => Language::Glg,
            0x14 => Language::Isl,
            0x15 => Language::Ita,
            0x17 => Language::Lat,
            0x18 => Language::Lav,
            0x19 => Language::Lux,
            0x1A => Language::Lit,
            0x1B => Language::Hun,
            0x1C => Language::Mlt,
            0x1D => Language::Nld,
            0x1E => Language::Nor,
            0x1F => Language::Oci,
            0x20 => Language::Pol,
            0x21 => Language::Por,
            0x22 => Language::Ron,
            0x23 => Language::Roh,
            0x24 => Language::Srp,
            0x25 => Language::Slk,
            0x26 => Language::Slv,
            0x27 => Language::Fin,
            0x28 => Language::Swe,
            0x29 => Language::Tur,
            0x45 => Language::Zul,
            0x46 => Language::Vie,
            0x47 => Language::Uzb,
            0x48 => Language::Urd,
            0x49 => Language::Ukr,
            0x4A => Language::Tha,
            0x4B => Language::Tel,
            0x4C => Language::Tat,
            0x4D => Language::Tam,
            0x4E => Language::Tgk,
            0x4F => Language::Swa,
            0x51 => Language::Som,
            0x52 => Language::Sin,
            0x53 => Language::Sho,
            0x56 => Language::Rus,
            0x57 => Language::Que,
            0x58 => Language::Pst,
            0x59 => Language::Pan,
            0x5A => Language::Per,
            0x5C => Language::Ori,
            0x5D => Language::Nep,
            0x5F => Language::Mar,
            0x60 => Language::Mol,
            0x61 => Language::Mal,
            0x63 => Language::Mkd,
            0x65 => Language::Kor,
            0x66 => Language::Khm,
            0x67 => Language::Kaz,
            0x69 => Language::Jpn,
            0x6A => Language::Ind,
            0x6B => Language::Hin,
            0x6C => Language::Heb,
            0x70 => Language::Gre,
            0x75 => Language::Chi,
            0x77 => Language::Bul,
            0x78 => Language::Ben,
            0x7D => Language::Arm,
            0x7E => Language::Ara,
            0x7F => Language::Amh,
            _ => Language::Unknown,
        }
    }
}

impl Serialize for Language {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        serializer.serialize_str(&self.to_string())
    }
}

impl fmt::Display for Language {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Language::Na => write!(f, "Unknown/NA"),
            Language::Alb => write!(f, "Albanian"),
            Language::Amh => write!(f, "Amharic"),
            Language::Ara => write!(f, "Arabic"),
            Language::Arm => write!(f, "Armenian"),
            Language::Ben => write!(f, "Bengali"),
            Language::Bre => write!(f, "Breton"),
            Language::Bul => write!(f, "Bulgarian"),
            Language::Cat => write!(f, "Catalan"),
            Language::Ces => write!(f, "Czech"),
            Language::Chi => write!(f, "Chinese"),
            Language::Cym => write!(f, "Welsh"),
            Language::Dan => write!(f, "Danish"),
            Language::Deu => write!(f, "German"),
            Language::Eng => write!(f, "English"),
            Language::Epo => write!(f, "Esperanto"),
            Language::Est => write!(f, "Estonian"),
            Language::Eus => write!(f, "Basque"),
            Language::Fae => write!(f, "Faroese"),
            Language::Fin => write!(f, "Finnish"),
            Language::Fra => write!(f, "French"),
            Language::Fry => write!(f, "Frisian"),
            Language::Gle => write!(f, "Irish"),
            Language::Glg => write!(f, "Galician"),
            Language::Gre => write!(f, "Greek"),
            Language::Heb => write!(f, "Hebrew"),
            Language::Hin => write!(f, "Hindi"),
            Language::Hrv => write!(f, "Croatian"),
            Language::Hun => write!(f, "Hungarian"),
            Language::Ind => write!(f, "Indonesian"),
            Language::Isl => write!(f, "Icelandic"),
            Language::Ita => write!(f, "Italian"),
            Language::Jpn => write!(f, "Japanese"),
            Language::Kaz => write!(f, "Kazakh"),
            Language::Khm => write!(f, "Khmer"),
            Language::Kor => write!(f, "Korean"),
            Language::Lat => write!(f, "Latin"),
            Language::Lav => write!(f, "Latvian"),
            Language::Lit => write!(f, "Lithuanian"),
            Language::Lux => write!(f, "Luxembourgish"),
            Language::Mal => write!(f, "Malay"),
            Language::Mar => write!(f, "Marathi"),
            Language::Mkd => write!(f, "Macedonian"),
            Language::Mlt => write!(f, "Maltese"),
            Language::Mol => write!(f, "Moldavian"),
            Language::Nep => write!(f, "Nepali"),
            Language::Nld => write!(f, "Dutch"),
            Language::Nor => write!(f, "Norwegian"),
            Language::Oci => write!(f, "Occitan"),
            Language::Ori => write!(f, "Oriya"),
            Language::Pan => write!(f, "Punjabi"),
            Language::Per => write!(f, "Persian"),
            Language::Pol => write!(f, "Polish"),
            Language::Por => write!(f, "Portuguese"),
            Language::Pst => write!(f, "Pushtu"),
            Language::Que => write!(f, "Quechua"),
            Language::Ron => write!(f, "Romanian"),
            Language::Roh => write!(f, "Romansh"),
            Language::Rus => write!(f, "Russian"),
            Language::Sho => write!(f, "Shona"),
            Language::Sin => write!(f, "Sinhalese"),
            Language::Slk => write!(f, "Slovak"),
            Language::Slv => write!(f, "Slovene"),
            Language::Som => write!(f, "Somali"),
            Language::Spa => write!(f, "Spanish"),
            Language::Srp => write!(f, "Serbian"),
            Language::Swa => write!(f, "Swahili"),
            Language::Swe => write!(f, "Swedish"),
            Language::Tam => write!(f, "Tamil"),
            Language::Tat => write!(f, "Tatar"),
            Language::Tel => write!(f, "Telugu"),
            Language::Tgk => write!(f, "Tajik"),
            Language::Tha => write!(f, "Thai"),
            Language::Tur => write!(f, "Turkish"),
            Language::Ukr => write!(f, "Ukrainian"),
            Language::Urd => write!(f, "Urdu"),
            Language::Uzb => write!(f, "Uzbek"),
            Language::Vie => write!(f, "Vietnamese"),
            Language::Zul => write!(f, "Zulu"),
            Language::Unknown => write!(f, "UNKNOWN"),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u16)]
pub enum UserApplication {
    Reserved = 0x000,
    Sls = 0x002,
    Tpeg = 0x004,
    Spi = 0x007,
    Dmb = 0x009,
    Filecasting = 0x00D,
    Fis = 0x00E,
    Journaline = 0x044A,

    Unknown(u8), // fallback for unmapped (0..=255 only)
}

impl From<u16> for UserApplication {
    fn from(value: u16) -> Self {
        match value {
            0x000 => UserApplication::Reserved,
            0x002 => UserApplication::Sls,
            0x004 => UserApplication::Tpeg,
            0x007 => UserApplication::Spi,
            0x009 => UserApplication::Dmb,
            0x00D => UserApplication::Filecasting,
            0x00E => UserApplication::Fis,
            0x044A => UserApplication::Journaline,
            val => UserApplication::Unknown((val & 0xFF) as u8),
        }
    }
}

impl fmt::Display for UserApplication {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            UserApplication::Reserved => write!(f, "Reserved"),
            UserApplication::Sls => write!(f, "SLS"),
            UserApplication::Tpeg => write!(f, "TPEG"),
            UserApplication::Spi => write!(f, "SPI"),
            UserApplication::Dmb => write!(f, "DMB"),
            UserApplication::Filecasting => write!(f, "Filecasting"),
            UserApplication::Fis => write!(f, "FIS"),
            UserApplication::Journaline => write!(f, "Journaline"),
            UserApplication::Unknown(v) => write!(f, "Unknown(0x{:02X})", v),
        }
    }
}

impl Serialize for UserApplication {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        serializer.serialize_str(&self.to_string())
    }
}
